name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [main]
  release:
    types: [published]

# based on https://github.com/pypa/gh-action-pypi-publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -U build "twine==5.1.1" "importlib_metadata==7.2.1"
      - name: Build package
        run: python -m build
      - name: Check package
        run: twine check dist/*

      # We do this, since failures on test.pypi aren't that bad
      #  - name: Publish to Test PyPI
      #    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      #    uses: pypa/gh-action-pypi-publish@v1.9.0
      #    with:
      #      user: __token__
      #      password: ${{ secrets.test_pypi_password }}
      #      repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution ðŸ“¦ to PyPI
        if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
